<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Om Shri Ganeshay Namah</name>
   <tag></tag>
   <elementGuidId>5fd88928-1683-4531-b377-4748feea3eb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.PZPZlf.ssJ7i.xgAzOe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Om Shri Ganeshay Namah&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>17528e88-9669-42dd-90c6-512e440d4163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PZPZlf ssJ7i xgAzOe</value>
      <webElementGuid>3d4c78b1-69a0-465e-b2b5-8a4c97857f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>10a4494a-baf8-4769-91c3-e54fa603bc40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attrid</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>163ab1e8-4b56-482c-a1ac-a54cc0f99d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>b05b5cb5-ebc6-48ed-b07b-72585e7b7781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Om Shri Ganeshay Namah</value>
      <webElementGuid>787b8cc6-bd9e-4cd7-b9ce-3ef0cef60614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rcnt&quot;)/div[@class=&quot;XqFnDf&quot;]/div[1]/div[@class=&quot;kp-wholepage-osrp&quot;]/div[@class=&quot;FAoEle&quot;]/div[@class=&quot;HdbW6 MjUjnf VM6qJ&quot;]/div[@class=&quot;hHq9Z&quot;]/div[1]/div[@class=&quot;KsRP6&quot;]/div[@class=&quot;MDY31c&quot;]/div[@class=&quot;QpPSMb&quot;]/div[@class=&quot;DoxwDb&quot;]/div[@class=&quot;PZPZlf ssJ7i xgAzOe&quot;]</value>
      <webElementGuid>578634c3-d942-4b42-a6be-2925652dff6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rcnt']/div[2]/div/div/div[3]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>d507254e-b5b1-417d-929b-a9599738e05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='general feedback'])[1]/following::div[14]</value>
      <webElementGuid>3a12b257-da6b-4966-b15a-9a0613a0769d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TV program'])[1]/preceding::div[1]</value>
      <webElementGuid>480f38a7-2ab6-4201-a35b-d6928a5f23b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About this result'])[1]/preceding::div[4]</value>
      <webElementGuid>8395b507-7d63-4f5f-b407-8d46c894aef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Om Shri Ganeshay Namah']/parent::*</value>
      <webElementGuid>c1c7d10a-0dfc-4ef5-aadc-1913574eab76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>a0e850f3-1d0c-484e-b2ae-93c14145690d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Om Shri Ganeshay Namah' or . = 'Om Shri Ganeshay Namah')]</value>
      <webElementGuid>e438bc1c-32b7-4d3e-a871-6ab40a2fb3bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
