<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_SuccessFactors - snowyhydroT1</name>
   <tag></tag>
   <elementGuidId>e9a4539c-bba7-4cb4-9fe5-19901c34eafd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='test-service-provider-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#test-service-provider-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;SuccessFactors - snowyhydroT1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9941b1ac-c83c-45a0-9504-f4bb99d54ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ids-heading-2</value>
      <webElementGuid>a6c39584-2151-4564-8086-22719633d415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>test-service-provider-name</value>
      <webElementGuid>88f0d167-8925-40e3-854d-2a30fe1d3fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SuccessFactors - snowyhydroT1</value>
      <webElementGuid>1a33554f-39db-4674-a166-852d9de6149a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test-service-provider-name&quot;)</value>
      <webElementGuid>4eb06331-4b9b-4f4e-877b-2049f5fcbbd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='test-service-provider-name']</value>
      <webElementGuid>5f1f484e-27cb-437f-bcbd-e3e4ed0a1aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body']/main/div/div/div[3]/div/h1</value>
      <webElementGuid>f807fa98-cdc9-418d-a752-8a09ee3d9297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::h1[1]</value>
      <webElementGuid>1f5e1791-2711-4bcc-9c32-c7b06bd13f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name'])[1]/preceding::h1[1]</value>
      <webElementGuid>81f6c9da-f22b-43c6-b45d-14c30668db94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::h1[1]</value>
      <webElementGuid>68c94796-4c86-418f-b09f-b23b9be916b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h1</value>
      <webElementGuid>cd3be24b-b977-4b42-afed-edc45960520e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'test-service-provider-name' and (text() = 'SuccessFactors - snowyhydroT1' or . = 'SuccessFactors - snowyhydroT1')]</value>
      <webElementGuid>34066da1-cb1f-4223-8892-f299a6b172e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
