<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Homescreen_ShadowRoot_Parent_Searchbar</name>
   <tag></tag>
   <elementGuidId>c25ecf72-bec7-42bc-b6e4-be8ca1db7d8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>xweb-shellbar-search-input#search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/TitleBar/HomeScreen_ShadowRoot_ParentMain_Banner</value>
      <webElementGuid>ad35b4fe-7377-4ad6-bca6-0f3651031a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>31eb73ff-86ae-4002-a8c2-f9fcff333c4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
