<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HomeScreen_ShadowRoot_Parent2_ProfileButton</name>
   <tag></tag>
   <elementGuidId>fd3a0eb9-486f-4b82-8117-2996dd25c4f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ui5-button-sf-header#ui5wc_1-item-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ui5wc_1-item-3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ui5-button-sf-header</value>
      <webElementGuid>2ca788e8-3e7a-40fc-853e-1525ab37afa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui5-shellbar-button ui5-shellbar-image-button</value>
      <webElementGuid>afa83c49-ad44-4358-b580-349393913525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>profile</value>
      <webElementGuid>94f5c53f-987f-4d32-a010-741205f3b9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui5wc_1-item-3</value>
      <webElementGuid>cedd422f-544f-4f39-bd9d-7a5686e7e601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip</name>
      <type>Main</type>
      <value>Account Navigation for Ambarish Dash ‎(adash)‎</value>
      <webElementGuid>95abb440-6c67-4be3-bb28-b676971d8603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/header[@class=&quot;ui5-shellbar-root ui5-shellbar-with-searchfield&quot;]/div[@class=&quot;ui5-shellbar-overflow-container ui5-shellbar-overflow-container-right&quot;]/div[@class=&quot;ui5-shellbar-overflow-container-right-child&quot;]/ui5-button-sf-header[@id=&quot;ui5wc_1-item-3&quot;]</value>
      <webElementGuid>84d71410-f0e8-4e8e-8f74-8647398d1d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/TitleBar/HomeScreen_ShadowRoot_Parent1_Banner</value>
      <webElementGuid>2f3a441d-b173-4773-b8b0-fa1ae62145a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9c0b99af-06af-4afe-8c9e-6c24b10bb599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>b60a2681-00e6-4ac3-a926-4d5872d3032c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ui5-button-sf-header[@id = 'ui5wc_1-item-3']</value>
      <webElementGuid>b3270725-18ad-45b7-ad0c-9e9e0f9ec607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
