<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HomeScreen_ShadowRoot_ParentMain_Banner</name>
   <tag></tag>
   <elementGuidId>494cde08-f87f-4b53-b188-5b552dacdbbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>xweb-shellbar.sfEnsureSAPTheme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/xweb-shellbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>xweb-shellbar</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>xweb-shellbar</value>
      <webElementGuid>7809b9d3-a8f0-4a59-b8a0-901f16826550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sfEnsureSAPTheme</value>
      <webElementGuid>98fc2bda-6e96-449a-b941-ad99cb4f3aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>33821685-5b10-4b00-810b-d697ae06e18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>sf-header-shellbar</value>
      <webElementGuid>40441f02-503d-4d61-8364-e0832488d74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>.sfThemeRevealer{display:none}</value>
      <webElementGuid>26e0713a-9c79-40cb-91ed-a6e9ba10407b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[@class=&quot;Shell_shellBar__uauJv&quot;]/xweb-shellbar[@class=&quot;sfEnsureSAPTheme&quot;]</value>
      <webElementGuid>730718b8-f38b-49c7-a62f-4bd50fbd13fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/xweb-shellbar</value>
      <webElementGuid>a9c258ed-38ad-406e-8b65-18eacb8b60de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good morning!'])[1]/preceding::xweb-shellbar[1]</value>
      <webElementGuid>6d6eb460-339b-46ad-920b-4c8d45334408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Actions'])[1]/preceding::xweb-shellbar[1]</value>
      <webElementGuid>5f4d8ad8-7a97-4998-bb3a-9099dda82b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//xweb-shellbar</value>
      <webElementGuid>c52369c4-1526-4eb5-a943-76250d45434c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//xweb-shellbar[(text() = '.sfThemeRevealer{display:none}' or . = '.sfThemeRevealer{display:none}')]</value>
      <webElementGuid>2637ba75-649a-4297-b425-8c0dec469491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
