<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProxyPopup_ParentMain_OkButton</name>
   <tag></tag>
   <elementGuidId>0e2dcf10-d517-4a47-bb12-9c6bd214e150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ui5-static-area-item-sf-header[data-ui5-stable=&quot;shellbar-proxy-static&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
