<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProxyPopup_Parent1_UserName</name>
   <tag></tag>
   <elementGuidId>6e17a9ec-4622-4e34-a4cc-82252f804036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>xweb-shellbar-search-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/Homepage/ProxyPopup_ParentMain_SelectTargetUser</value>
      <webElementGuid>e16d124b-cd6f-41c7-b9c5-0038aa0674a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8cd43cd8-4f3d-4f2f-a613-4780aa5c626c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
