<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tileButton_Payroll</name>
   <tag></tag>
   <elementGuidId>a49b23fb-cd8f-4bcb-bf96-1e17921929b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[title='Payroll']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
