<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HomeScreen_ShadowRoot_Parent1_ProfileButton</name>
   <tag></tag>
   <elementGuidId>63746dff-2990-4ab0-b16b-10f09a1b44dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ui5-shellbar-sf-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shellbarContainer']/ui5-shellbar-sf-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Home Admin Centre Careers Company Info Compensation Learning My Employee File On&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ui5-shellbar-sf-header</value>
      <webElementGuid>8d9aeb7e-7b93-49b2-b703-890fe6a83cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shellbar</value>
      <webElementGuid>1dc0c58b-5bf6-4a8f-a7e2-aa377a673b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>shellbar</value>
      <webElementGuid>925bdb64-952d-4aa5-afea-5bd4a50b7411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-static-stable</name>
      <type>Main</type>
      <value>shellbar-static</value>
      <webElementGuid>40ad7d7c-c2fd-45a2-8e69-99328962c5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sap-ui-fastnavgroup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>350125d0-e74d-4da5-8041-c23402ec3fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>breakpoint-size</name>
      <type>Main</type>
      <value>L</value>
      <webElementGuid>a2f6c751-6a49-4746-a8a5-aff883613c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>primary-title</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>c9f5c9db-d1be-4e85-a1de-09df882821f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomeAdmin CentreCareersCompany InfoCompensationLearningMy Employee FileOnboardingPayrollRecruitingReportingSAP JamSuccessionPeopleView</value>
      <webElementGuid>4e3e6829-c479-4c16-862f-1934df036014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[1]/div[@id=&quot;shellbarContainer&quot;]/ui5-shellbar-sf-header[@id=&quot;shellbar&quot;]</value>
      <webElementGuid>c2ff2e3b-db30-4bd5-88ca-9bc4adeae983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>33b4c64f-6b4c-4ae1-bf29-931523a0c765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/HomeScreen_ShadowRoot_ParentMain_ProfileButton</value>
      <webElementGuid>1bf21887-9aff-4db2-851c-6f48707a9e47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shellbarContainer']/ui5-shellbar-sf-header</value>
      <webElementGuid>46335d68-8a5e-4032-830c-32ccffe4460b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>8464545d-d9c3-4225-86be-9c8b512f77ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ui5-shellbar-sf-header[@id = 'shellbar' and (text() = 'HomeAdmin CentreCareersCompany InfoCompensationLearningMy Employee FileOnboardingPayrollRecruitingReportingSAP JamSuccessionPeopleView' or . = 'HomeAdmin CentreCareersCompany InfoCompensationLearningMy Employee FileOnboardingPayrollRecruitingReportingSAP JamSuccessionPeopleView')]</value>
      <webElementGuid>75ff1024-f198-47b6-841e-d4959e9636f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
