<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HomeScreen_ShadowRoot_Parent2_ProfileButton</name>
   <tag></tag>
   <elementGuidId>fd3a0eb9-486f-4b82-8117-2996dd25c4f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui5wc_1-item-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ui5wc_1-item-3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ui5-button-sf-header</value>
      <webElementGuid>fd5511a4-f365-4677-8d68-45d3bfbfae41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui5-shellbar-button ui5-shellbar-image-button</value>
      <webElementGuid>273e4796-0b3f-4337-96f3-cc47f0931704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui5-stable</name>
      <type>Main</type>
      <value>profile</value>
      <webElementGuid>463fe8d3-b18c-4e3c-988e-05027da11183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui5wc_1-item-3</value>
      <webElementGuid>e513bc51-0eed-41c0-a31e-970d23954be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip</name>
      <type>Main</type>
      <value>Account Navigation for Ambarish Dash ‎(adash)‎</value>
      <webElementGuid>667bb186-81f9-47ed-805a-ad1f612bb6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/header[@class=&quot;ui5-shellbar-root ui5-shellbar-with-searchfield&quot;]/div[@class=&quot;ui5-shellbar-overflow-container ui5-shellbar-overflow-container-right&quot;]/div[@class=&quot;ui5-shellbar-overflow-container-right-child&quot;]/ui5-button-sf-header[@id=&quot;ui5wc_1-item-3&quot;]</value>
      <webElementGuid>7889cbb3-1158-45d3-8265-b511115b3e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1080026a-13b5-405a-b17e-ba80fef06722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SuccessFactors Home/HomeScreen_ShadowRoot_Parent1_ProfileButton</value>
      <webElementGuid>26bf07e4-9b05-497e-a390-c473375e8e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>bcdf3872-99b0-4625-ae15-6f29cebe57de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ui5-button-sf-header[@id = 'ui5wc_1-item-3']</value>
      <webElementGuid>946499f0-5f8a-43f4-b937-c6d34bf585a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
