<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProxyResult_ShadowRoot_MainParent</name>
   <tag></tag>
   <elementGuidId>59c97777-ab20-4c22-813b-8334e94e72bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ui5-static-area-item-sf-header[data-ui5-stable=&quot;shellbar-proxy-search-static&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
