<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_itemPrice</name>
   <tag></tag>
   <elementGuidId>0d87dc8d-5d1f-4e66-8819-dfd7638cabbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='inventory_item']/div[2]/a/div[contains(text(),'${itemName}')]/ancestor::div[@class='inventory_item']/div[@class='pricebar']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d8cf1f12-4140-4337-93c6-651643a27185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1727866071759</value>
      <webElementGuid>15133727-3768-44df-a7ee-39ecde593f93</webElementGuid>
   </webElementProperties>
</WebElementEntity>
