<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>temp</name>
   <tag></tag>
   <elementGuidId>018f4b41-d7ab-46e2-9928-72dc0779d7bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__text164</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
